[keyboard]
name = "sofle-rs"
vendor_id = 0x4c4b
product_id = 0x4643
serial_number = "vial:f64c2b3c:000001"
board = "nrf52840"
usb_enable = true

[layout]
rows = 5
cols = 12
layers = 5
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5)             (0,6) (0,7) (0,8)  (0,9) (0,10) (0,11)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5)             (1,6) (1,7) (1,8)  (1,9) (1,10) (1,11)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5)             (2,6) (2,7) (2,8)  (2,9) (2,10) (2,11)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (4,5) (4,6) (3,6) (3,7) (3,8)  (3,9) (3,10) (3,11)
            (4,0) (4,1) (4,2) (4,3) (4,4) (4,7) (4,8) (4,9) (4,10) (4,11)
"""

[[layers]]
name = "main"
keys = """
grv   1   2    3    4     5                   6     7     8     9    0    No 
esc   Q   W    E    R     T                   Y     U     I     O    P    bspc
Tab   A   S    D    F     G                   H     J     K     L    scln quot
lsft  Z   X    C    V     B      No     No    N     M     comm  .    slsh rsft
          lcmd lopt lctl  No     ent    spc   No    rctl  ropt  rcmd
"""

[storage]
# Set `clear_storage` to false to NOT clear all the stored info when the keyboard boots
clear_storage = false 

[ble]
enabled = true
default_tx_power = 8
ble_use_2m_phy = false

[split]
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
row_pins = ["P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]
col_pins = ["P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 6

[split.peripheral.matrix]
row_pins = ["P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]
col_pins = ["P0_09", "P0_10", "P1_11", "P1_13", "P1_15", "P0_02"]

[rmk]
# This is the default ZMK debounce time, I'll stick with the RMK default for instance.
# debounce_time = 5
ble_profiles_num = 3
